messages:
  changed-crew: "&7Your atlas has changed to: %crew%"
  changed-other-crew: "&7You changed the atlas of &f%player% &7to: %crew%"
  reset-crew: "&7Your atlas has been reset! Type &a/atlas &7to pick a new one."
  reset-other-crew: "&7You reset the atlas of &f%player%"
  must-reset-crew: "&cYou must reset your atlas before choosing another one!"
  already-reset: "&7Your atlas is already reset! Use &a/atlas &7to choose one."
  gave-token: "&f%player% &7has been given an Atlas Reset Token"
  cant-use-eco-item: "&cYour atlas must be %crew% &cto use that item!"
  cant-use-eco-armor: "&cYour atlas must be %crew% &cto equip that armor!"
  cant-choose-crew: "&cYou don't have permission to choose that crew!"
options:
  crew-reset-item: EMERALD
  crew-reset-item-name: "&aATLAS ARMORY RESET"
  crew-reset-item-lore:
    - "&7Use this to reset your Atlas."
gui:
  title: "&8Atlas"
  item-text:
    - "&8» %crew% &fAtlas &8«"
    - " "
    - "&fChoose wisely. Each atlas has its own special"
    - "&fattributes that give you positive buffs."
    - " "
    - "%crew% Buffs"
  item-text-buff: "&f • %buff%"
  # This is the visual layout of the crews GUI. Every line is a new row.
  # Every 'A' represents a different atlas (crew).
  layout:
    - "         "
    - "  AAAAA  "
    - "         "
  filler-icon: "AIR"